name: Create PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ./*.md
      - LICENSE
      - .circleci/*
      - .gitlab-ci.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install awscli-local

      - name: Deploy Preview
        uses: LocalStack/setup-localstack@v0.2.2
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-backend: ephemeral
          state-action: start
          skip-ephemeral-stop: 'true'
          include-preview: 'true'
          preview-cmd: |
            # Add your custom deployment commands here. 
            # Below is an example for the Image resizer application.
            bin/deploy.sh