name: Sync repo to Gitlab
on: [ push, delete, workflow_dispatch ]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@gitlab.com:localstack.cloud/samples/sample-serverless-image-resizer-s3-lambda.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}